MINUTES_PER_HOUR = 60
MINUTES_PER_DAY = 24 * MINUTES_PER_HOUR
METERS_PER_MILE = 1609.344
EARTH_RADIUS_MILES = 3958.8
MILES_PER_DEGREE_LATITUDE = 69.0

POLYLINE_PRECISION = 6
MAX_CYCLE_HOURS = 70
MILES_DECIMALS = 1
HOURS_DECIMALS = 2

USER_AGENT = "Milemark-ELD-Trip-Planner/1.0"
HTTP_TIMEOUT_SECONDS = 8
HTTP_RETRIES = 1
HTTP_BACKOFF_SECONDS = 0.2
HTTP_POOL_SIZE = 20

GEOCODE_CACHE_SECONDS = 24 * 3600
ROUTE_CACHE_SECONDS = 24 * 3600
MIN_QUERY_LENGTH = 2
MAX_SEARCH_RESULTS = 8
DEFAULT_SEARCH_RESULTS = 6
CONTIGUOUS_US_BBOX = "-125,24,-66,50"
IGNORED_PLACE_TYPES = frozenset({"county", "state", "country", "region", "district"})
IGNORED_OSM_KEYS = frozenset(
    {"railway", "public_transport", "highway", "waterway", "natural", "boundary"}
)
