import type { DailyLog, TripPlan } from '../types/trip'

export const sampleLog: DailyLog = {
  date: '2026-10-05',
  day_number: 1,
  from_location: 'Richmond, VA',
  to_location: 'Newark, NJ',
  total_miles: 324.8,
  totals: { off_duty: 16.08, sleeper: 0, driving: 5.92, on_duty: 2 },
  segments: [
    { status: 'off_duty', activity: 'before_trip', start_minute: 0, end_minute: 360 },
    { status: 'on_duty', activity: 'pickup', start_minute: 360, end_minute: 420 },
    { status: 'driving', activity: 'drive_to_dropoff', start_minute: 420, end_minute: 775 },
    { status: 'on_duty', activity: 'dropoff', start_minute: 775, end_minute: 835 },
    { status: 'off_duty', activity: 'after_trip', start_minute: 835, end_minute: 1440 },
  ],
  remarks: [
    { minute: 360, location: 'Richmond, VA', note: 'Pickup, loading (on duty)' },
    { minute: 420, location: 'Richmond, VA', note: 'Driving to drop-off' },
    { minute: 775, location: 'Newark, NJ', note: 'Drop-off, unloading (on duty)' },
    { minute: 835, location: 'Newark, NJ', note: 'Trip complete, off duty' },
  ],
  recap: {
    on_duty_today: 7.92,
    cycle_total: 7.92,
    available_tomorrow: 62.08,
    last_five_days: 7.92,
    restart_taken: false,
  },
  details: {
    driver_name: 'John E. Doe',
    carrier_name: "John Doe's Transportation",
    main_office_address: 'Washington, D.C.',
    home_terminal_address: 'Richmond, VA',
    vehicle_numbers: '123, 20544',
    shipping_document: '101601',
    commodity: 'Paper goods',
  },
}

export const samplePlan: TripPlan = {
  summary: {
    total_miles: 324.8,
    driving_minutes: 355,
    on_duty_minutes: 120,
    total_minutes: 475,
    start: '2026-10-05T06:00:00',
    end: '2026-10-05T13:55:00',
    days: 1,
    fuel_stops: 0,
    breaks: 0,
    rests: 0,
    restarts: 0,
  },
  route: {
    polyline: '_p~iF~ps|U_ulLnnqC_mqNvxq`@',
    precision: 5,
    waypoints: [
      { role: 'current', label: 'Richmond, VA', lat: 37.5385, lng: -77.4343 },
      { role: 'pickup', label: 'Richmond, VA', lat: 37.5385, lng: -77.4343 },
      { role: 'dropoff', label: 'Newark, NJ', lat: 40.7357, lng: -74.1724 },
    ],
    legs: [
      { from_label: 'Richmond, VA', to_label: 'Richmond, VA', miles: 0, drive_minutes: 0 },
      { from_label: 'Richmond, VA', to_label: 'Newark, NJ', miles: 324.8, drive_minutes: 354 },
    ],
  },
  stops: [
    {
      id: 0,
      kind: 'start',
      title: 'Start',
      location: 'Richmond, VA',
      lat: 37.5385,
      lng: -77.4343,
      mile: 0,
      arrive: '2026-10-05T06:00:00',
      depart: '2026-10-05T06:00:00',
      duration_minutes: 0,
      day_number: 1,
    },
    {
      id: 1,
      kind: 'pickup',
      title: 'Pickup',
      location: 'Richmond, VA',
      lat: 37.5385,
      lng: -77.4343,
      mile: 0,
      arrive: '2026-10-05T06:00:00',
      depart: '2026-10-05T07:00:00',
      duration_minutes: 60,
      day_number: 1,
    },
    {
      id: 2,
      kind: 'dropoff',
      title: 'Drop-off',
      location: 'Newark, NJ',
      lat: 40.7357,
      lng: -74.1724,
      mile: 324.8,
      arrive: '2026-10-05T12:55:00',
      depart: '2026-10-05T13:55:00',
      duration_minutes: 60,
      day_number: 1,
    },
  ],
  logs: [sampleLog],
}
